version: "3"
services:
  # grapqlexpressservice:
  #   build:
  #     dockerfile: "nodeserver.Dockerfile"
  #   #image: ngauth_frontend
  #   container_name: grapqlexpress_container
  #   ports: 
  #     - "3500:3500"
  #   volumes:
  #     - "/graphql/node_modules"
  #     - ".:/graphql"

  jsonserverservice:
    build:
      dockerfile: "jsonserver.Dockerfile"
    #image: ngauth_frontend
    #container_name: jsonserver_container
    ports: 
      - "3000:3000"
    volumes:
      - "/db/node_modules"
      - ".:/db"